Explore the commands relevant to the following identities/outputs with different input
values.

1. Identity
2. ones
3. zeros
4. sum
5. size
6. Linear spaced data
7. random

In [2]:
import numpy as np

In [25]:
def printn(*args):
  print(*args, end="\n\n")

In [26]:
printn(np.identity(3))
print(np.identity(10))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [27]:
printn(np.ones(5))
printn(np.ones((2, 3)))
print(np.ones((3, 4, 2)))

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [28]:
printn(np.zeros(5))
printn(np.zeros((2, 3)))
print(np.zeros((3, 4, 2)))

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [31]:
printn(np.sum([2, 3, 4]))
printn(np.sum([[0, 1, 2], [3, 4, 5]]))
printn(np.sum([[0, 1, 2], [3, 4, 5]], axis=0))
printn(np.sum([[0, 1, 2], [3, 4, 5]], axis=1))
print(np.sum([2, 3, 4, 5], dtype=np.float32))

9

15

[3 5 7]

[ 3 12]

14.0


In [37]:
printn(np.size(3))
printn(np.size([3, 1]))
printn(np.size([[3, 4, 2], [2, 3, 8]]))
printn(np.size([[3, 4, 2], [2, 3, 8]], axis=0))
print(np.size([[3, 4, 2], [2, 3, 8]], axis=1))

1

2

6

2

3


In [40]:
printn(np.linspace(2, 5))
printn(np.linspace(2, 5, num=10))
printn(np.linspace(2, 5, num=10, retstep=True))
printn(np.linspace(2, 5, num=10, endpoint=False))

[2.         2.06122449 2.12244898 2.18367347 2.24489796 2.30612245
 2.36734694 2.42857143 2.48979592 2.55102041 2.6122449  2.67346939
 2.73469388 2.79591837 2.85714286 2.91836735 2.97959184 3.04081633
 3.10204082 3.16326531 3.2244898  3.28571429 3.34693878 3.40816327
 3.46938776 3.53061224 3.59183673 3.65306122 3.71428571 3.7755102
 3.83673469 3.89795918 3.95918367 4.02040816 4.08163265 4.14285714
 4.20408163 4.26530612 4.32653061 4.3877551  4.44897959 4.51020408
 4.57142857 4.63265306 4.69387755 4.75510204 4.81632653 4.87755102
 4.93877551 5.        ]

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]

(array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ]), 0.3333333333333333)

[2.  2.3 2.6 2.9 3.2 3.5 3.8 4.1 4.4 4.7]



In [47]:
printn(np.random.rand(2))
printn(np.random.rand(2, 3))
printn(np.random.randint(4))
printn(np.random.randint(4, 10))
printn(np.random.randint(4, 10, size=10))
printn(np.random.randint(4, 10, size=(3, 2)))
printn(np.random.randint([2, 3, 5], 10))

[0.13485348 0.08420806]

[[0.7697039  0.39201063 0.94859768]
 [0.59882193 0.02257388 0.98614049]]

2

9

[5 8 5 6 8 5 9 8 9 6]

[[4 9]
 [5 5]
 [5 5]]

[2 6 9]

